<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sampritis-MacBook-Pro.local" failures="1" tests="2" name=" t" time="9.675" errors="0" timestamp="2024-05-09T20:33:42 IST">
  <testcase classname="rahulshettyacademy.ErrorValidation" name="LoginErrorValidation" time="1.091"/>
  <testcase classname="rahulshettyacademy.ErrorValidation$SubmitOrderTest" name="ProductErrorValidation" time="2.111">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at rahulshettyacademy.ErrorValidation$SubmitOrderTest.ProductErrorValidation(ErrorValidation.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!--  t -->
